import type { Finding, GradeResult, ParsedDiff } from "./types";
import { fileName } from "./diff";

const CHECKLISTS: Record<string, string> = {
  "secret-literal": "Rotate the credential if it ever reached a remote; move to env/secret store.",
  "entropy-secret": "Confirm the flagged value is not a real credential.",
  "conflict-marker": "Finish resolving the conflict; run the build after resolving.",
  "debug-leftover": "Strip debug output or switch to the project logger.",
  "todo-marker": "File an issue or finish the marked work before merge.",
  "sensitive-path": "Get sign-off from the owner of this security-sensitive area.",
  "dependency-change": "Vet new deps: maintenance, publish age, typosquatting risk.",
  "lockfile-mismatch": "Regenerate and commit the lockfile.",
  "migration-no-rollback": "Add a down/rollback step or document irreversibility.",
  "env-var-undeclared": "Document the variable in .env.example and deploy config.",
  "missing-tests": "Add coverage for the changed behavior.",
  "large-diff": "Split into stacked PRs if practical.",
};

export function buildMarkdownReport(diff: ParsedDiff, findings: Finding[], grade: GradeResult): string {
  const lines: string[] = [];
  lines.push("## PreFlight risk report");
  lines.push("");
  lines.push(`**Verdict: ${grade.grade} — ${grade.verdict}** (risk score ${grade.score})`);
  lines.push("");
  const fileNames = diff.files.map(fileName);
  lines.push(
    `Analyzed ${diff.files.length} file(s), +${diff.totalAdded} / -${diff.totalRemoved} lines: ${fileNames.slice(0, 8).join(", ")}${fileNames.length > 8 ? ", …" : ""}`,
  );
  lines.push("");
  if (findings.length === 0) {
    lines.push("No findings. PreFlight detected nothing risky in this diff.");
  } else {
    lines.push("| Severity | File | Line | Finding |");
    lines.push("| --- | --- | --- | --- |");
    for (const f of findings) {
      lines.push(`| ${f.severity} | \`${f.file}\` | ${f.line ?? "—"} | ${f.message} |`);
    }
  }
  lines.push("");
  lines.push("### Reviewer checklist");
  lines.push("");
  const seen = new Set<string>();
  for (const f of findings) {
    if (seen.has(f.ruleId)) continue;
    seen.add(f.ruleId);
    const item = CHECKLISTS[f.ruleId];
    if (item) lines.push(`- [ ] ${item}`);
  }
  if (seen.size === 0) lines.push("- [x] Nothing flagged — standard review applies.");
  lines.push("");
  lines.push("_Generated by [PreFlight](https://github.com/sharonbasovich/preflight) — analysis ran locally; the diff never left the browser._");
  return lines.join("\n");
}
